version: 2.1
orbs:
  node: circleci/node@5.0.2
workflows:
  test:
    jobs:
      - test
jobs:
  test:
    docker:
      - image: cimg/node:lts
    # To use Remote Caching, uncomment the next lines and follow the steps below.
    environment:
     TURBO_TOKEN: $TURBO_TOKEN
     TURBO_TEAM: $TURBO_TEAM
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn lint
      - run:
          command: yarn build